---
title: "syllabus cse economics optional"
author: "dhananjaya"
date: "28/07/2022"
output: html_document
---

#PAPER 1 {.tabset}

Advanced Micro Economics:

Marshallian and Walrasiam Approaches to Price determination.

 Alternative Distribution Theories: 

Ricardo, Kaldor, Kaleeki

Markets Structure: 

Monopolistic Competition, Duopoly, Oligopoly.

Modern Welfare Criteria: 

Pareto Hicks & Scitovsky, Arrow’s Impossibility    Theorem, A.K. Sen’s Social Welfare Function. 

Advanced Macro Economics:

Approaches to Employment Income and Interest Rate determination:  Classical, Keynes (IS-LM) curve, Neo classical synthesis and New classical, Theories of Interest Rate determination and Interest Rate Structure.

Money - Banking and Finance:

 Demand for and Supply of Money: 

Money Multiplier Quantity Theory of Money (Fisher, Pique and Friedman) and Keyne’s Theory on Demand for Money, Goals and Instruments of Monetary Management in Closed and Open Economies. Relation between the Central Bank and the Treasury. Proposal for ceiling on growth rate of money.

Public Finance and its Role in Market Economy: 

In stabilization of supply, allocation of resources and in distribution and development. Sources of Govt. revenue, forms of Taxes and Subsidies, their incidence and effects. Limits to taxation, loans, crowding-out effects and limits to borrowings. Public Expenditure and its effects.

International Economics:
(a) Old and New Theories of International Trade

(i) Comparative Advantage

(ii) Terms of Trade and Offer Curve.

(iii) Product Cycle and Strategic Trade Theories.

(iv) Trade as an engine of growth” and theories of under development in an open economy.

(b) Forms of Protection: Tariff and quota.

(c) Balance of Payments Adjustments: Alternative Approaches.

(i) Price versus income, income adjustments under fixed exchange rates,

(ii) Theories of Policy Mix

(iii) Exchange rate adjustments under capital mobility

(iv) Floating Rates and their Implications for Developing Countries: Currency Boards.

(v) Trade Policy and Developing Countries.

(vi) BOP, adjustments and Policy Coordination in open economy macro-model.

(vii) Speculative attacks

(viii) Trade Blocks and Monetary Unions.

(ix) WTO: TRIMS, TRIPS, Domestic Measures, Different Rounds of WTO talks.

5. Growth and Development:
(a)    (i) Theories of growth: Harrod’s model,

(ii) Lewis model of development with surplus labour

(iii) Balanced and Unbalanced growth,

(iv) Human Capital and Economic Growth.

(v) Research and Development and Economic Growth 

(b) Process of Economic Development of Less developed countries: Myrdal and Kuzments on economic development and structural change: Role of Agriculture in Economic Development of less developed countries.

(c) Economic development and International Trade and Investment, Role of Multinationals.

(d) Planning and Economic Development: changing role of Markets and Planning, Private- Public Partnership

(e) Welfare indicators and measures of growth – Human Development Indices. The basic needs approach.

(f) Development and Environmental Sustainability – Renewable and Non Renewable Resources, Environmental Degradation, Intergenerational equity development.


Indian Economy in Pre-Independence Era:
Land System and its changes, Commercialization of agriculture, Drain theory, Laissez faire theory and critique. Manufacture and Transport: Jute, Cotton, Railways, Money and Credit.

#PAPER 2

Indian Economy after Independence:
A. The Pre Liberalization Era:

(i) Contribution of Vakil, Gadgil and  V.K.R.V. Rao.

(ii) Agriculture: Land Reforms and land tenure system, Green Revolution and capital formation in agriculture,

(iii) Industry Trends in composition and growth, Role of public and private sector, Small scale and cottage industries.

(iv) National and Per capita income: patterns, trends, aggregate and Sectoral composition and changes their in.

(v) Broad factors determining National Income and distribution, Measures of poverty, Trends in poverty and inequality.

B. The Post Liberalization Era:

(i) New Economic Reform and Agriculture:  Agriculture and WTO, Food processing, Subsidies, Agricultural prices and public distribution system, Impact of public expenditure on agricultural growth.

(ii) New Economic Policy and Industry: Strategy of industrialization, Privatization, Disinvestments, Role of foreign direct investment and multinationals.

(iii) New Economic Policy and Trade: Intellectual property rights: Implications of  TRIPS, TRIMS, GATS and new EXIM policy.

(iv) New Exchange Rate Regime: Partial and full convertibility, Capital account convertibility.

(v) New Economic Policy and Public Finance: Fiscal Responsibility Act, Twelfth Finance Commission and Fiscal Federalism and Fiscal Consolidation.

(vi) New Economic Policy and Monetary system. Role of RBI under the new regime.

(vii) Planning: From central Planning to indicative planning, Relation between planning and markets for growth and decentralized planning: 73rd and 74th Constitutional amendments.

(viii)    New Economic Policy and Employment: Employment and poverty, Rural wages, Employment Generation, Poverty alleviation schemes, New Rural, Employment Guarantee Scheme.