---
title: "Daily Test -002"
output: html_document
---


**Solve any 3**

1. Show that the lexicographic preference relation satisfies rationality.

2. Prove that the MRS of a homothetic preference relation is homogeneous of degree zero.

3. Prove that homotheticity does not imply homogeneity.

4. what is the economic interpretation of  convexity of indifference curves ?

5. prove that If a preference relation satisfies monotonicity and continuity, then there exists a utility function u(∙) representing such preference relation.

6. what is the difference between quasi-concavity and strict quasi -concavity of utility functions ?

7. which of the following function satisfies convexity and strict convexity ? 
    - $ax_1 +bx_2$
    
    - $min(ax_1+bx_2)$
    
    - $ax_1^{\frac{1}{2}} bx_2^{\frac{1}{2}}$
    
    - $ax_1^2 bx_2 ^2$
    
8. What is a utility function ?

9. why indifference curve are not supposed to intersect each other ?

10. If $U=-2x-3y$ ,  $P_x=0$ , $P_y=2$ and income =100 $ what will be the optimal bundle for the consumer ?

### Answers {.tabset .tabset-fade .tabset-pills}

#### 1

#### 2

#### 3

#### 4


#### 5

#### 6

#### 7

#### 8

#### 9

#### 10

#### Reference

- Advance Microeconomics , Felix Munoz Garcia
- Advance Economic theory , H.L.Ahuja


