---
title: "Daily Test-004"
output: html_document
---


1. $U=X^(\frac{1}{3}) Y^(\frac{2}{3})$ 

$P_X= 10 $ 

$P_Y=20$

and the utility target of $u\bar$

find the consumption bundle that solves the expenditure minimization problem. 


2. Explain the relationship between utility maximization problem and expenditure minimization problem.(150 words)

3. Eric has a weekly income of I = $40$, which he allocates between purchasing goods x and y. When the price of good x is $4$ and the price of good y is also $4$, Eric purchases 3 units of good x and 7 units of good y in equilibrium. Now suppose that the price of good x falls to $2$.
(a) Find the equations of his original and new budget lines and represent them graphically.
(b) Suppose that Eric’s new equilibrium bundle is 5 units of good x and 5 units of good y. Does this new bundle violate WARP? Explain why or why not.
(c) Suppose that Eric’s new equilibrium bundle contains 4 units of good y. How many units of good x must be consumed such that our equilibrium allocation does not violate WARP?


4. Consider a situation where there are two goods in the world:food and garbage. Naturally, garbage in this context would be considered a “bad,” while food is considered a good. Suppose that the price for both types of goods is positive.
(a) Would a rational person consume any  garbage in   equilibrium ? Why or why not?
(b) Under what condition or conditions would a consumer be willing to consume a positive amount of garbage?


#### Answers {.tabset .tabset-fade .tabset-pills}

##### 1

##### 2

##### 3

##### 4


##### References

- Advance Microeconomics , Felix Munoz Garcia
- intermediate Microeconomics , Felix Munoz Garcia
