---
title: "ISI MSQE"
output: html_document
---

draft

0. [Syllabus](https://www.isical.ac.in/~admission/IsiAdmission/Syllabus/MSQE_Syllabus-2022.pdf)

1. Solve PYQ. [2015-21](https://www.isical.ac.in/~admission/IsiAdmission/PreviousQuestion/Questions-MSQE.html) , [2004-14](https://www.isical.ac.in/~deanweb/MSQESQ.html)  

2. PYQ solutions [Econschool](https://www.econschool.in/resources/past-year-exams)


**Microeconomics**

Look at the question paper. Everything is more or less an Intermediate level optimization problem with sound  economic logic. You need to know optimal consumption , production , properties of market equilibrium, game theory , optimal wages ,endowment as well as general equilibrium.

for basic production you can refer 

1. [osborne university_of _toronto](https://www.economics.utoronto.ca/osborne/2x3/tutorial/index.html)

You can read hal varian and snyder, nicholson. This is the traditional combination. But Hal varian itself does not have numericals. It has a 

1. [test bank](https://drive.google.com/file/d/1Jjvuch8LcU19oxNbe4cxq805ZrrDBNMy/view?usp=sharing)  

2. [workbook](https://drive.google.com/file/d/1X9ulQit0ffHJyZgm0dFuHFHO5BpEvgP2/view?usp=sharing)  

3. [workout solutions](https://drive.google.com/file/d/1buEQoOhTVummdiRNzGtFbBZG97VVufyS/view?usp=sharing). 

You can do it selectively as most of us do not have time to solve all the question.snyder nicholson end chapter exercise are helpful both for pea and peb perspective.

but there are 2 books which works as a nice alternative and have integrated combination  of theory and numerical.

i. [Intermediate microeconomics by samiran banerjee, a tool building approach]()
2. [Intermediate micro a step by step guide by garcia]() 


just look at the books you will know.

samiran banerjee chapter 2 has a portion called non competitive budget. read that. in garcia book you will know how to find income and substitution effect and intersting utility functions.

special mention- amit goyals 

1. [you tube playlist](https://www.youtube.com/c/AmitGoyal-econschool/playlists)  

i. demand 

ii. general equilibrium

iii. solved problems 



if you want a video approach for numerical solution browse videos of these channels.

i. [economics in many lessons](https://www.youtube.com/c/EconomicsinManyLessons/playlists)



other thing you can follow

i. [economics stack exchange]()

ii. [amit goyals quora page on microeconomics solution]()

if you want to solve further general equilibrium question and more difficult problems you can refer foreign university pages. They provide good problem sets. These problem sets are more or less copied by coaching institutes in India . If you ever take coaching you will realize that many peb practice  questions are either from 

1. [mit ocw]()

2. [problems sets by professors]()

try this problem set by 

1. [mawalker](http://www.u.arizona.edu/~mwalker/Exercises/)


there are some question comes from hecksher olhin theory and trade models. use this link by 
1. [suranovic](http://internationalecon.com/Trade/Tch60/Tch60.php)

some problem sets for trade model 

1. [alander 441](http://www-personal.umich.edu/~alandear/courses/441/ps/) . 

solve problem set 2 and 3 only.


**Macroeconomics**

They are asking basic question. Solow model seems to be their favorite question

Try to read directly these two if you have already read froyen/makiw/blanchard

- [ucla 102](https://fgeerolf.com/econ102/) (If you like maths)
- [george lukynov](https://sites.google.com/view/glukyanov/teaching)

Then you can read any of one book. One book may not have all the chapters so you can just use other book to read that chapter. I am saying this because nobody has time to read everything.

list

1. dornbush and fisher

2. mankiw adavnce macro

3. **abel and bernake**

4. **froyen**

Btw there is always internet.


i. [economicurtis](https://www.youtube.com/c/economicurtis/playlists)

ii. [liam malloy](https://www.youtube.com/user/liammalloy/playlists)



**Mathematics**

1. [cornell Good question project](http://pi.math.cornell.edu/~GoodQuestions/materials.html#GQ)

2. [Tomato solution isi by ctanujit](https://www.ctanujit.org/uploads/2/5/3/9/25393293/isi_ebook.pdf)

3. [convexity by amit goyal](https://www.youtube.com/playlist?list=PLUJGfL_499TLYEd-9IO1DmQKwm6Mtdt4u)

4. [essence of calculus by 3blue1brown](https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr)

5. [Essence of linear algebra by 3blue1brown](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

6. [osborne notes utoronto](https://mjo.osborne.economics.utoronto.ca/index.php/tutorial/index/1/toc)

7. Fundamental Methods of Mathematical Economics , chiang ,wainwright [buy](https://www.amazon.in/Fundamental-Methods-Mathematical-Economics-Chiang/dp/125909734X/ref=pd_sim_3?pd_rd_w=BB3o4&pf_rd_p=779929c3-4bad-491c-b925-3ec03c91d856&pf_rd_r=DDK1B840GPX9YQQPHXKT&pd_rd_r=f9ca1000-9a63-442b-8aaa-d2abc4ab206f&pd_rd_wg=CrStu&pd_rd_i=125909734X&psc=1)  , [drive]()

8. [paul maths](https://tutorial.math.lamar.edu/)

9. MTH 101 iit k [LECTURE NOTES](https://home.iitk.ac.in/~psraj/mth101/lecture_notes.html)   [PRACTICE PROBLEMS](https://home.iitk.ac.in/~psraj/mth101/practice-problems.html)

10. [PBWORKS Quizes](http://scherk.pbworks.com/w/browse/#view=ViewFolder&param=Quizzes)

11. [mathematics book for isi msqe by ctanujit](https://www.ctanujit.org/uploads/2/5/3/9/25393293/mathematics_book_for_isi_msqe_exam.pdf)

12. [parimal parag proofs](https://ece.iisc.ac.in/~parimal/2015/proofs/)


Some other sources /practice MCQ

13. [imo maths](https://imomath.com/index.cgi?page=mathTexts)

14. [sanfoundary](https://www.sanfoundry.com/1000-engineering-mathematics-questions-answers/)

15. [Jee focus](https://jeefocus.com/app/#page=category&secid=3)

16. RD SHARMA OBJECTIVES  [BOOK 1](https://drive.google.com/file/d/0B0d-UkWYmTPhZkZBV0ppbjU5dmc/view?resourcekey=0-MJzbrvRoLbu0Q_oq6asSqg)   [BOOK 2](https://drive.google.com/file/d/0B0d-UkWYmTPhVzI1WFcwTDFQT1E/view?resourcekey=0-1p5KKJJ3su8hju9I55bd2Q)

17. [NCERT Exmplers problem](https://ncert.nic.in/exemplar-problems.php?ln=) 

18. [Math insight](https://mathinsight.org/index/general)

19. [Libretext books](https://math.libretexts.org/Bookshelves)

20. [kouba](https://www.math.ucdavis.edu/~kouba/)

21. [kouba problem sets](https://www.math.ucdavis.edu/~kouba/ProblemsList.html)


List 

|Topic|Reading list |Link|
|---|---|---|
|Properties of polynomials, Reminder theorm ,zeros of polynomials|[byju](https://byjus.com/maths/polynomial/)  [theory of equation byju ](https://byjus.com/jee/theory-of-equations/)|
|basic methods for solving functional equation| [imo math](https://imomath.com/index.cgi?page=basicMethodsFunctionalEquations)|
|


**statistics**

1. [A first course on probability by sheldon ross](http://library.lol/main/1e7b981a2f8c320c81d356b375bb6433)

2. [John E. Freund's Mathematical Statistics with Applications](https://libgen.li/edition.php?id=138634838)

3. [open intro statistics](http://library.lol/main/4c23047d7037b3e12265f35d89fb1782)

4. [MIT OCW INTOR TO STATISTICS (lecture notes+problem sets)](https://ocw.mit.edu/courses/14-30-introduction-to-statistical-methods-in-economics-spring-2009/pages/assignments/)

5. [Intro to probability and random variable](https://www.probabilitycourse.com/preface.php)

6. [IIT MTH 676 INTRO TO ECONOMETRICS](https://home.iitk.ac.in/~shalab/course3.htm)

7. [SANFOUNDARY](https://www.sanfoundry.com/1000-probability-statistics-questions-answers/)

8. [STATLECT](https://www.statlect.com/)

9. [mit ocw stat problem sets](https://ocw.mit.edu/courses/14-30-introduction-to-statistical-method-in-economics-spring-2006/pages/assignments/)

10. [Degroot, schervish](http://library.lol/main/4fa98d3b0be2986a9e05ff01048bac7a)

11. [devore](https://drive.google.com/file/d/1xbDrkV4nCUIN_Jd2vq3AMgAe5KwdKn7T/view?usp=sharing)

12. [gujrati econometrics]()






some online testbank

1. [applied economics griffiths](https://wps.pearsoned.co.uk/ema_uk_he_griffiths_appecon_12/204/52362/13404752.cw/index.html)

2. [howells](https://wps.pearsoned.co.uk/ema_uk_he_howells_econmoney_4/98/25261/6466832.cw/index.html)



**international trade**

1. [int trade saylor academy](https://saylordotorg.github.io/text_international-trade-theory-and-policy/)



ALL THE BOOKS AND AVILABLE SOLUTION

|Book |Solution file|
|---|---|
|[Oliver blanchard , Macroeconomics](https://drive.google.com/file/d/15QWl0VH0lJMfpHCFRvjk0P6mM-WYcKG6/view?usp=sharing)|[drive](https://drive.google.com/file/d/1xJW3faVn8_ZazrDKQEjh8NnnuJ6Sv_Fr/view?usp=sharing)|
|[Froyen, Macroeconomics](https://drive.google.com/file/d/1oNX7_q-gsRNR04wkoWTgpvYJL1ipk7T1/view?usp=sharing)|
|[dorrbursch](https://drive.google.com/file/d/1yxK4SWCrLgWcNnIZ-PJ2ZL7P3GkiopGo/view?usp=sharing)||
|[snyder nicholson](https://drive.google.com/file/d/1HqnOvcGbYUl-8Yw2uvYuYN-K3CRwGGpr/view?usp=sharing)||
|[perloff](https://drive.google.com/file/d/1CihRPgUyNI_cS6O73NyySjFy_-rRy6_k/view?usp=sharing)||




