---
title: "PYQ 2014 CSE Mains Optional Paper II"
author: "dhananjaya"
date: "`r Sys.Date()`"
output: html_document
---

**1.Answer the following questions in about 150 words each**:

# {.tabset}



## 1.(a)

Land system during British period was responsible for sustained poverty in Indian and stagnant growth of Indian economy. Discuss.**


## Answer:

- British land revenue system raised some problems which led to sustained poverty and stagnant growth in the Indian economy.

Issues associated with British land revenue system

**Disruption of traditional mechanism**

- Landlord now had property rights over the lands in his jurisdiction, instead of tiller. Tillers became tenants who could be summarily dismissed. It pushed many tenants towards severe poverty.

**Growth of ABSENTEE LANDLORDISM**

- Rent payment in money format led to growth of moneylenders. Moneylenders used to charge high interest rate. It reduced surplus for farmers and led to lower investments in agriculture.

**Prevented growth of capitalist farming in India** 

- It led to decline in productivity . According to Blyn growth rate was just 0.72%. Thus India has to resort to food import. 

**Reasons**

- Small size of landholdings because large landowners leased out their holdings to many small farmers;
- Zamindar didn’t invest because his land could be confiscated on non payment of rent 
- Tenant didn’t invest because of frequent transfer of land and all benefits accruing to the land owner
- Given high rents, many farmers moved from growing food crops to cash crops like cotton and sugarcane, leading to famines. Thus it can be said that  land system during British period was responsible for sustained poverty in Indian and stagnant growth of Indian economy.

## Reference 

something




## 1.b

**Write about the policy of discriminating protection during the British rule and its impact on industrial development in India.**

Answer:

Until the First World War, the government followed a policy of LAISSEZ FAIRE in the promotion of industry. However to strengthen finances and pacify Indian nationalist, after world war 1 government adapted policy of discriminating protection. It raised some of the tariff on imports.

Economic Consequence of discrimination protection 

Some Increase in tariff take place, hence it Protected the Indian industries. This led to diversification of industrial base and new factories came up in sugar, iron and steel, matches, paper.
Manufacturing grew @ 5.6% between 1920 and 1938
Industries like Tata and Birla expanded for example eg Tata entered into Aviation sector.
However protection was only to the industries which had Natural Advantage. These were mostly those goods that did not create Competition with Britain . But, their competition was more with other countries especially Japan. Hence gains were limited that to to few industries. As a result of this discriminations export  share of Britain rose to 35%.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) Why socialist model of development could not bring about equitable distribution of income in India and the country remained on a slow growth trajectory of 3 to 3.5 percent for a long time? Discuss.

Answer:

Looking at socio economic condition prevailing at that time, India adapted socialist order. However it could not bring about equitable distribution of income and faster growth of the economy. 

Reasons of failure of socialist model 

In planning system focus was on capital industries rather than agriculture and consumer industries. High gestation period of capital industries deprived common Indians. Thus benefits of growth did not reach to marginal sections.

System of import controls which was designed to conserve scarce foreign exchange, actually served only to provide open-ended protection for domestic producers against foreign competition. It led to a high cost and low quality domestic production structure. Thus it slowed growth of the  manufacturing.

Protections to SSI and excessive regulation of large scale industries prevented growth of manufacturing. Thus employment creation was very low. In addition to that there were many regulations like MRTP, Licensing, FERA, etc. Thus all paved way for crony socialism. Benefits of growth was cornered by few people. It led to unequitable distribution.

Looking at that situation of socialist model, India decided to open up and go for market economy.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(d) Specify the main factors which hindered trickle-down in Indian economy and agenda of ‘inclusive growth’ is being pressed into for economic justice.

Answer:

The trickle-down theory, argues that growth would lead to more jobs, more output, more income and less poverty as the growth and higher incomes at the top end will move at the lower end and to the poor.

Factors which hindered trickle down in Indian economy

Indian economic development in earlier year has given less importance to the agriculture and consumer goods and gave more importance to capital good manufacturing. Capital good manufacturing are labor intensive and high gestation period thus it does not benefitted poor.

After 1980 service sector grow faster than agriculture and manufacturing. Service sector is less employment elastic than the manufacturing or agricultural sector. Thus it led to jobless growth. Jobless growth is major reason for slow trickle down.

India before 1991 saw crony socialism and later after reforms it was converted to crony capitalism. It benefitted rich and excluded poor. At the same time there was little public investment on education and health. It limited capability development of poor. This factors together lead to slow and incomplete trickle down in the Indian economy.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(e) What are the consequences of deviation from socialistic pattern of society and mixed economy particularly for the persons below the poverty line? Explain.

Answer:

In 1991 India shifted from socialistic pattern of society to the liberalisation. Lets analyse its consequences for the person below BPL.

World Bank study by Gaurav Datt suggest that poverty declined by 1.36 percentage points per annum after 1991, compared to that of 0.44 percentage points per annum prior to 1991. Telndulkar committee report also suggest that poverty rate declined from 45% in 1991 to 22% in 2011. This indicates reforms were successful in reducing poverty. It raised the standard of life for BPL families.

But Himanshu’s study suggest that it was PDS and MGNREGA which reduced poverty and not the reforms. It can be seen that India after reforms is seeing jobless growth. It is impacting BPL families most. Inequalities have also increased thus relative standard of living is worsen for poor. Privatization of school and hospitals and low public spending on education and hospitals are impacting poor.

After 1991 reforms absolute poverty decreased. But it marginally improved standard of living of poor. There is need to focus on inclusive growth so that poor also get equal benefit of growth.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

2. Answer the following questions:

(a) Elaborate growth-mediated security and support-led security strategies of poverty alleviation given by Jean Dreze and Amartya Sen.

Answer:

Amartya Sen and Jean Dereze have brought out two approaches to reduce poverty – growth mediated security and support-led security. Poverty reduction and income expansion achieved through high economic growth is called ‘growth mediated security’.

Support led security is achievement of growth and poverty reduction through wide ranging public support is given in areas such as ’employment provision, income redistribution, health care, education and social assistance in order to improve distribution without waiting for a transformation in the level of general affluence.

Sen advocates approach of building capability through investment in education and health. He suggest that growth of India is not reflected in significant reduction in poverty, employment generation and human capital development. Thus there is now need to make growth inclusive. State should investment in education and health right away without waiting for being rich and then redistribution. 

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(b) Do you think Gandhian vision of development is still relevant in India? Explain with reasons.

Answer:

Gandhian vision of development was based on decentralization development by empowering local self governments at grass root level. Socialism is another basic philosophical entity of Gandhianism. Although Gandhian view of socialism is not radical in its approach but it aspires for a classless society with no poverty, no hunger, no unemployment and education and health for all. 

Gandhi aims at what we may call sustainable development. Thus his ideas are still relevant in today’s India. His emphasis on decentralization development is still relevant. Its success can be seen in the form of MGNREGA and community led development. His vision to make cottage industries as engine of growth can be way towards Atmanirbhar Bharat. 

His views on school are very relevant in todays world. Nayi Talim school system gives practical education to children. Its modified version can help to fulfill dream of skill India. 

Development should be targeted to eradicate poverty, hunger, unemployment. It should provide health and education to all. These are exactly objectives of many government schemes. 

His ideas may not be adapted as it is. His opposition to mechanization can be counter productive in today’s world. But basic philosophy of Gandhian development can still be guiding light for India’s development process. 

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) Why are land reforms still not complete in India? What are the obstacles in its way? Elaborate.

Answer:

Land reforms has important components like Zamindari abolition, tenancy regulation, land ceiling and land consolidation. However it has limited success. According to P S Appu, by 1992, ownership right conferred to only 4% of cultivated area. According to Haque, on the national scale only 1/3rd of the consolidatable area has been consolidated.

Reasons for failure of land reforms 

Zamindar used loopholes in clause of personal cultivation. voluntary surrender clause was used as a guise. It lead to forceful eviction.
To evade land ceiling clause, zamindar made benami transfers or transferred land in the names of other members of a households.
Property right was recognized as fundamental right. It led to several disputes in courts.
Many states did not passed law on time. UP took four and half year to pass law.
Strong tenancy regulation led to informalization of tenancy.
Tenants were renamed as farm servants or sharecroppers.
In many states land ceiling limit was very high.
Indian’s have emotional attachment with land. Thus it created problems for land consolidation.
PS Appu blamed apathy of bureaucracy and politicians for unsuccessful land reforms. Thus except abolition of Zamindari all other reforms more or less incomplete.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

3. Answer the following questions:

(a) Why Green Revolution lost its steam and India needs yet another Green Revolution or Evergreen Revolution? Discuss.

Answer:

In 1965 government of India introduced green revolution program. It was characterized by use High yield verities, chemical fertilizers, machineries, farmer education, government procurement, minimum support price, etc.

Between 1967-1970 food production rose by 35%. Food grain production increased from 75mt to 105mt in 1971. Agriculture growth increased from 0.8% to 3%. India became self sufficient in food production. Our current food grain production is 250mt.  It was helpful in commercialization of agriculture.

However Green revolution assistance was cereal centric. Thus its success was limited to cereals. Pulses production dropped from 61mg per capita to 42 mg per capita now.  It is seen that it was limited to Punjab, Haryana and western UP. Eastern and north eastern sector was ignored. 

Increased mechanization reduced employment elasticity of the agriculture. It increased rural distress. It is also seen that increased fertilizer use deteriorated environment and soil quality. Productivity might further decrease due to global warming and climate change. 

The technologies used in green revolution are showing decreasing return to scale. In the recent time agricultural growth has been stagnated. It showed that impact of green revolution was limited and there is need of sustainable evergreen revolution.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(b) Highlight the structural changes in Indian economy before 1991.

Answer:

Structural changes in economy before 1991 can be analyzed in three phases. First phase between 1951 to 1965. Second phase between 1965 to 1980 and last phase between 1980 and 1990

1951 – 1965

After independence India adapted strategy of planned economy. During this period focus was on setting up capital industries. PSU were given role of commanding heights. In this period agricultural share goes down and capital industries share increased in GDP.

1965-1980

This phase in known for inward orientation and industrial stagnation. During this period India realized importance of agriculture. Policy of green revolution was launched during this period. It made India self sufficient.

However policies like MRTP, FERA, reservation for small scale industries, etc created inefficiencies. It stagnated industrial growth. This led to stagnation in GDP growth rate at 3.5%.

1980-1990

During this period growth started exceeding 5% mark. According to Subramaniam pro business attitude change and reforms like MRTP relaxation, decrease in tax law helped economy to grow. Panagaria called it most significant structural change. 

India’s growth rate in pre reform period was low compared to its potential. Low growth can be contributed to excessive regulation, anti business environment and licence raj.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) Examine the Labour Policy of India and its impact on employment (labour) market in Indian economy.

Answer:

Note : Answer to this question is not provided as it was old debate. Now after Atmanirbhar Bharat its going to change. 

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

4. Answer the following questions:

(a) National Rural Employment Guarantee Scheme should be reoriented to create productive permanent assets to promote employment and generate income in the rural sector. Critically evaluate.

Answer:

In 2005 MGNREGA was started. Its aim was to provided 100 days guaranteed employment to unskilled population. The scheme has potential to change fate of rural area. 

MGNREGA is aimed at unskilled population. There is need of skilling of MNREGA workers through Deen Dayal Upaadhyaya Grameen Kaushal Yojana for vertical mobility of labour towards skilled work. This will help realizing the dream of Skill India. It will increase productivity and thus will create better opportunities for workers.

The scheme should be converged with other schemes of agriculture, irrigation, road transport and animal husbandry, water management etc. There is need of sharing of costs for each component – wage and material by center and state so that there is no bias towards high labor cost projects. 

Permitting contractors within the overall ceiling of material component to include skilled and semi-skilled workers would lead to speedy and effective implementation of the projects and improve the quality of assets created. It would improve the employment availability as well as income generations.

Thus there is need to reorient MGNREGA. MGNREGA 2.0 should aim at creating productive permanent assets, to promote employment and generate income in the rural sector.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(b) What are the factors responsible for large number of farmers suicides in relatively richer Indian States? Examine.

Answer:

Relatively richer states like Maharashtra and Karnataka are seeing increasing number of farmer suicides. There are various socio economic reasons.

Factors Responsible for large number of farmers suicide 

Economic Factors

Day by day cost of farming has increase. There is surge in input cost, fertilizers cost, labor cost. But at the same time agriculture marker is highly volatile. It led to frequent losses for the farmers.  It creates distress for farmers. 

Due to volatility in prices there is less surplus remain to repay the loan and run the livelihood. Thus there are cases of loan defaults for farmers. 

Environmental Factors

Farming activity is highly dependent on environmental factors. Drought or heavy rainfall may damage crop. In the Maharashtra region suicide is prevalent in Vidarbha. It is rainfed region. A drought season destroys crop which leads to farmer distress.

Social Factors

Social evils like dowry, alcoholism is pushing farmers towards debt trap. It led to suicide for farmers.

We need to tackle socio, economic and environmental problems at the same time to deal with problems of suicide.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) In Indian economy, dichotomy of development emerged during the pre-reform period despite efforts of holistic development. Delineate the factors responsible for it.

Answer:

1980s is often cited as that breaking point when India made a transition from an economic laggard to one of the fastest growing nations of the world. Any increase in our GDP and per capita income is supposed to imply an increase in our living standards. However growth has not equated to human development and thus increased living standards.

Even though the growth rate of our per capita income rose from 1.7% in 1950-1980 period to an average of 4% thereafter, the core human development parameters continued to be dismal . This is reflected by the fact that India’s relative rank in human development among 177 countries has risen by only two positions from 128 in 1999 to 126 in 2004. Education, health and security continued to be ignored which led to poor development.

Amartya Sen emphasized, while the case of economic reforms of 1980s and 1991 correctly diagnosed too much governance in some sectors of the economy, it ignored the fact that India had too less governance in other fields like education, healthcare, social security, and land reforms. This led to dichotomy of growth and development.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

5. Answer the following questions in about 150 words each:

(a) Highlight the issues of Bhagwati-Sen controversy over tackling poverty and slow growth rate.

Answer:

There is debate going on between Sen and Bhagwati over issues of growth and distribution.

Bhagwati’s Approach 

Bhagwati focuses more on growth than distribution. He thinks more liberalization, privatization and foreign trade will promote growth. He points out that economic growth will lead to reduction in poverty. According to him economic growth will increase employment opportunities and thus reduces poverty. Economic growth increased revenue for the government thus government can now spend more on health, education and social welfare schemes. He suggested that in the country where the poor exceeds rich by large margin, redistribution will increase welfare of poor marginally. 

However empirical evidence confirms that growth not necessarily generates adequate employment & thus it will be difficult to tackle poverty. India is seeing similar jobless growth.

Sen’s Approach

Sen advocates approach of building capability through investment in education and health. Unlike Bhagwati he does not consider, growth first and then redistribution. He suggest that growth of India is not reflected in significant reduction in poverty, employment generation and human capital development. Thus there is now need to make growth inclusive. State should investment in education and health right away without waiting for being rich and then redistribution. He was not against liberalization but he gave priority to investment in education and health. However Sen’s view underplays importance of infrastructure and physical capital.

What required is balanced between strategy of Sen and Bhagwati. There is need to have equal emphasis on human capital development and rapid growth with capital accumulation. 

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(b) While Indian economic growth in recent years is services-led growth and Chinese model is manufacturing-led growth, show the implications of the two models for long-term sustainable development.

Answer:

India’s policy of liberalization was aimed at increasing industrial growth. However manufacturing share in GDP remain stagnated at 16% while service sector share increased to 60% from 40%. On other hand China’s share of manufacturing in GDP was highest. .

Service sector is less labor intensive, thus with growth India is not seeing growth in the employment. This jobless growth is creating problems of inequalities and unequal distribution. It also weakens fight against poverty. On other hand China’s manufacturing is labor intensive and was able to generate enough jobs. 

From the trade perspective, there is reluctance from world towards opening trade in service sector. Thus India is not able to exploit its trade potentials. Also over dependence on import for manufacturing goods can be problematic for economic sovereignty. 

Thus service  led growth with stagnant manufacturing may not good for long term sustainability. India has to work towards increasing its manufacturing growth.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) Employment pattern in India in post-reform period has moved in favour of contractual, casual and self-employment. How public sector employment deceleration would impact the future of labour (employment) market in India? Elaborate.

Answer:

Since 1991 to 2010, informal sector employment increased from 91% to 93 %. It is increasing casualization. Even in formal sector there is preference given for contractual workers. It might be because of complex and rigid labor system of India.

Impact of casualization on future labor market

In contractual employment, there is less incentive in investing in labour’s training. There is evidence that hiring contract workers today hurts a firm’s productivity tomorrow, precisely because contract workers do not accumulate “firm specific human capital”. It would impact long run growth trajectory.
There is increased contractualisation of government jobs. It might create difficulties for person to switch from government sector to private sector.
Worker right protection is absent. Thus it might lead to exploitation of labor.
In the economic shock unemployment rate might increase leading to further depression.
It might increase unwillingness to participate in labor force. It will encourage rent seeking over investing in productive activity.
The changing trend of casualization might not be good for long term. There is need to focus on creating social safety net and long term sustainable quality employment.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(d) Skill development and thereby raising productivity like that in China would be the only panacea for long-term growth in Indian economy. Discuss.

Answer:

Endogenous growth model suggest that for long run sustainable economic growth there is need to focus on human capital development. Without it growth process could be converging and stagnant. India is currently facing skill gap.

India skill report suggests that only 48% of graduated students are employable. Unskilled population hindrance development of manufacturing industry. With the advent of fourth industrial revolution it might aggravate problems of of unemployment and poverty. 

Skill development is an important driver to address poverty reduction by improving employability, productivity and helping sustainable enterprise development and inclusive growth. It facilitates a cycle of high productivity, increased employment opportunities, income growth and development.

The increase in productivity could be due to availability of skilled & healthy manpower; technological up gradation and innovative practices. Thus India has to focus on these factors to ensure long term sustainable growth.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(e) Second generation economic reforms are crucial for raising the growth rate of economy. Throw light on these dimensions.

Answer:

Second generation of economic reforms in the country gave special stress on fiscal reforms, financial reforms, structural reforms, labour law reforms etc.  

Fiscal reforms has to undertaken for broadening the income tax base and introducing GST. There is also need to streamline tax structure so that it become conducive to growth.

It is seen that complex and rigid labor laws are major hinderance in the development of manufacturing sector. Its streamlining will ensure the growth of manufacturing sector.

India has to work on improving Ease of Doing Business. It will help to attract foreign capital in India. Currently red tapism is hindering growth process. Single window system and digital system can reduce the delay.

Agriculture growth has been stagnated from long time. There is need to focus on agricultural reforms. Liberalisation of agriculture market and investment in the capital infrastructure will increase the growth rate of agriculture. 

Thus second generation will remove bottlenecks in the development of Indian economy. It will help us to achieve double digit growth rate.

Note : Most of the reforms are implemented. Another interest thing is second generation reform term was coined by IMF. But even IMF has not defined it. So basically you can write any reforms.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

6. Answer the following questions:

(a) What are the salient features of FRBM Act? Examine the criticisms labelled against it.

Answer:

To limit the fiscal deficit FRBM act was introduced.

Salient features of FRBM Act

It aims at reducing fiscal deficit to 6% (3% of the central government and 3% of the state government).
Revenue deficit should be eliminated.
Government in required to submit four documents in parliament Medium Term Fiscal Policy Statement, Fiscal Policy Strategy Statement, Macroeconomic Framework Statement and Medium Term Expenditure Framework Statement
On grounds of national security, calamity, etc, the set targets of fiscal deficits and revenue could be exceeded.
Criticism of FRBM act

It is criticized that 3% target of FRBM is arbitrarily set. Some also criticize that it puts excessive limit on government expenditure. However it is actually ensuring expenditure switching from revenue expenditure to capital expenditure. 

Another issue with FRBM act is that the limit on fiscal deficit is frequently breached and act is frequently amended. Thus NK Singh committee suggested using debt as the primary target for fiscal policy and that the target must be achieved by 2023.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(b) Discuss the issues involved in Capital Account Convertibility. In the light of this, explain India’s important Capital Account Liberalization measures.

Answer:

Capital account convertibility refers to, freedom to convert local financial assets into foreign financial assets and vice versa at market determined rates of exchange There are continuous demands for full capital account convertibility. However it has some issues involved. 

In the good economic situation full capital account convertibility might lead to excessive capital inflow appreciates currency. It affects our export competitiveness. Due to economic shock there could be large foreign out flow. It creates deficit in capital account which affects BoP. In 1997 similar situation was seen in ASEAN countries which destabilized their economies.

Thus India has not introduced full capital account convertibility. But it has introduced some measures for capital account liberalization.

Measures for Capital Account Liberalization

In many sectors automatic FDI is allowed
Indian corporate is allowed full convertibility in the automatic route up to $ 500 million overseas ventures (investment by Ltd. companies in foreign countries allowed).
Indian corporate is allowed to prepay their external commercial borrowings (ECBs) via automatic route if the loan is above $ 500 million.
Individuals are allowed to invest in foreign assets, shares, etc., up to the level of $ 2,50,000 per annum.
Unlimited amount of gold is allowed to be imported.
Gradually by fulfilling Tarapore Committee recommendations India should move towards full capital account convertibility. 

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) How global financial crisis and sovereign debt crisis of European nations exposed the disturbing role of speculative motive and fiscal imprudence? What lesson could India derive from it?

Answer:

The global financial crisis (GFC) refers to the period of extreme stress in global financial markets and banking systems between mid 2007 and early 2009. The European sovereign debt crisis was a period when several European countries experienced the collapse of financial institutions, high government debt, and rapidly rising bond yield spreads in government securities.

Theses crisis have some lessons for India. First lesson is that financial sector issues should not be overlooked. Any excessive credit expansion in financial market should be regulated on time. Any speculation should be controlled before it becoming bubble. 

Second lesson is that overleveraged state can be problematic. State should follow the fiscal imprudence. Excessive fiscal deficit and government deficit can damage macro economic framework of the country. It can also lead to sovereign debt default. In the medium term it can harm countries growth potential and credibility.

Third lesson is that in the globally linked world crisis anywhere is threat to economic development everywhere. Thus India should be vigilant on development of global crisis. In any such crisis government should be ready to deal it with fiscal, monetary, regulatory and policy tools.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

7. Answer the following questions:

(a) ‘Elitist bias’ and ‘crony capitalism’ have eclipsed the issues of efficiency and distributive justice in India. Elaborate.

Answer:

Crony capitalism is an economic system in which businesses thrive not as a result of risk, but rather as a return on money amassed through a nexus between a business class and the political class. It creates oligarchies and slows down growth.

According to Raghuram Rajan one of the greatest dangers to the growth of developing countries is the middle income trap, where crony capitalism creates oligarchies that slow down growth.

In India crony capitalism is helping few elite individuals to corner most of the generated wealth. It is impacting distributive issues in India. Economic Survey 2020 suggest that crony capitalism has impacted efficiency in India. Crony capitalism creates environment of protectionism and monopoly. It impacts both consumer and total welfare.

In India even after the reforms agriculture sector was largely ignored. It is employer of 50% workforce of India. The policy making largely focused on manufacturing and service sector. This elite biased impacted efficiency in the agriculture.

Thus it can be said that ‘elitist bias’ and ‘crony capitalism’ have eclipsed the issues of efficiency and distributive justice in India.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(b) Vitalization of rural economy is key to ‘inclusive growth’ which is possible through ‘strategic management’ and technological up gradation. Explain.

Answer:

India’s 65% population lives in rural area. India’s 50% workforce is dependent on agriculture. Agriculture is dominantly rural occupation thus vitalization of rural economy is key to inclusive growth.

Vitalisation of rural economy

Strategic Management

Strategic management involves setting objectives, analyzing the competitive environment,  evaluating strategies, and ensuring that government rolls out the strategies. Agriculture is strength of rural area. Government can set objectives of all round development around agriculture. It can focus on creating completive environment for the growth of agriculture and allied industries, government can focus on development of rural infrastructure. 

Technological up gradation

Access to internet in rural area will help in improvement of education. It also opens jobs opportunities in digital sector. Technological upgradation in agriculture sector improves productivity. Technology of food processing, storage, food transports adds value to the agricultural production. Rural area is dominated by MSMEs. Technological upgradation in MSMEs improves their profitability and thus employment opportunities. Technological upgradation of infrastructure reduces logistic cost. It will help to attract investment in rural area.

Thus vitalization of rural economy is key to ‘inclusive growth’ which is possible through ‘strategic management’ and technological up gradation.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) How could e-governance tackle the issues of corruption and inefficiency in the government sector to lead to higher growth rate in the economy? Discuss.

Answer:

Under the digital India scheme government is pushing for e governance initiatives. It has ability yo tackle issues of corruption and inefficiencies. 

The red tapism and corruption are hampering India’s growth rate. E governance can improve this. Single window system, form simplification and field reduction, online applications and tracking, etc can significantly reduce red tapism and corruption.

Tax system of India is reformed through faceless assessment. It reduces contact between officials and tax payers. Thus it reduces cases of corruption. Similarly now tax filing can be done online thus has become very simple process.

MyGov  aims to establish a link between Government and Citizens towards meeting the goal of good governance. It encourages citizens as well as people abroad to participate in various activities i.e. ‘Do’, ‘Discuss’, ‘Poll’, ‘Talk’, ‘Blog’, etc. People participation increases accountability and reduces corruptions. 

E governance can increases transparency and accountability of the system. Online process fastens the file movement. Thus it can be said that e governance, is a significant instrument of tackling the issues of corruption and inefficiency in the government sector.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

8. Answer the following questions:

(a) Subsidy is a contentious issue and roadblock in the WTO. Examine India’s stand for protecting its farmer’s interests.

Answer:

Subsidies are contentious issue and roadblock in the WTO. Developed and developing world are divided over the issues of subsidies. 

In the WTO developed countries are allowed to maintain trade distorting subsidies or ‘Amber box’ subsidies (AMS) to level of 5% of total value of agricultural output and for developing countries this figure was 10% of agricultural output. This domestic price support is calculated as the difference between the fixed external reference price prevailing between 1986-88.

According to developing countries including India the reference period of 1986-88 is outdated . Thee base year in general had an exceptionally lower prices also it fails to count in the high inflation in developing countries. Developing countries argue that they need to be given flexibility to stock enough grains for the food security of millions of their poor. 

Another contention is over domestic price support provided by developed country. Developed country have already used Amber box subsidies which are now restricted for the less developed countries. 

Developed countries are heavily subsidizing their agriculture by export subsidies, food aid program, credit guarantee scheme, etc. Farmer’s of the developed countries are also relatively rich. But now this WTO restrictions on agricultural subsidies are impacting food security and farmer welfare in developing countries.

India has taken firm stand that  will not accept any limits on subsidies on farm inputs such as seeds and fertilizers. India is committed to protect food security and welfare of the farmers.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(b) Write on the Look East Policy of India.

Answer:

Look East Policy of India was launched in 1991 by the Government of India led by the former Prime Minister Narasimha Rao. The objective was to develop political, economic and security co-operation with countries in Southeast Asia.

The results of India’s ‘Look East’ policy are also amply demonstrated in our growing economic interaction with the region. India’s trade with Asean has risen from US $2.4 billion in 1990, to US $23 billion in 2005. Our trade with the countries of the East Asia Summit has, similarly, risen from US $8 billion in 1990, to US $67.6 billion in 2005. This accounts for nearly 30% of our external trade. At the same time, the period has also seen an increase in FDI flows, both from India to the region and region to India.

In the present phase of our ‘Look East’ policy, we in India seek to deepen our economic integration by entering into Free Trade or Comprehensive Economic Partnership Agreements, both with Asean as a whole and with individual countries of the region. Such agreements are already under different stages of discussion or implementation with Singapore, Thailand, Malaysia and Indonesia.

In the recent time India wanted to increase ties with ASEAN. Thus Look East Policy has been replaced by the Act East Policy.

©opyright : abhishekdudhal.wordpress.com

———————————————————————————————————————————————————

(c) Write for and against FDI in retail trade of India.

Answer:

In India FDI in retail sector is not allowed. There are both support and opponents of allowing FDI in retail sector.

Why to allow FDI in retail trade?

FDI in retail trade will boost growth in the economy. Due to its economies of scale it generates many jobs from office assistant, delivery boy to high level management jobs. Due to less intermediaries it will benefit farmers. Due to its economies of scale, prices will be reduced. It will benefit to consumers. Also FDI in retail trade will boost infrastructure, storage facilities, new technology development. Thus FDI in retail sector can play conducive role in economic development.

Why not to allow FDI in retail trade?

Retail sector is employer of many small shopkeepers and households. Their volume is very low. On contrary FDI will have big pockets. They can buy goods at bulk quantity at low prices and thus can give heavy discount. It will disrupt economy of small shop keepers. Once the small shopkeepers economy weakens, large FDI players can establish monopoly. It will hurt consumer welfare in long run. Thus we need precautions to allow FDI in retail sectors.