---
title: "PYQ DSE 2018"
author: "dhananjaya"
date: "`r Sys.Date()`"
output: html_document
---
## DSE 2018

1. Let R be the set of real numbers and $f:R→R$ be a continuous and concave function. Which of the following statements is correct?

A.  $|f|$ must be concave

B. $−f$ must be concave

C. $f+f$ must be concave

D.  $f◦f$ must be concave


2. The maximum value off $(x,y) = (xy)^\frac{1}{2}$  , subject to $|x|≥|y|$ and $|x|+|y|≤1$  is

A. 1

B. 2

C. 0.5

D. 0.25

3. Consider an exchange economy with two agents, 1 and 2, and two goods, X and Y. Each agent’s consumption set is $R_+^2$ . The endowments of agents 1 and 2 are (10,1) and (0,9) respectively. (In any commodity bundle, the first entry is a quantity of X and the second one is a quantity of Y.) If $a > c$ , or $a=c$ and $b > d$ , then Agent 1 strictly prefers bundle $(a,b)$ to $(c,d)$. If $b > d$, or $b=d$ and $a > c$, then Agent 2 strictly prefers bundle (a,b) to (c,d). Which of the following allocations is competitive equilibrium allocation?

A. 1 gets (10,1) and 2 gets (0,9)

B. 1 gets (10,10) and 2 gets (0,0)

C. 1 gets (5,5) and 2 gets (5,5)

D. None of the above

E. Incorrect options provided for this question.


4.. Let R be the set of real numbers and let D be the set of functionsd: $R\times R→R$ that satisfy the following properties for all $x,y,z∈R$

$d(x,y)\geq 0$

$d(x,y) = 0$ if and only if $x=y$

$d(x,y) =d(y,x)$

$d(x,z)\leq d(x,y) +d(y,z)$

Which of the following is not a function inD?

A. d(x,y) = min{|x−y|, 1 }
B.
C. d(x,y) =

7. Letf : [0,1]→R be twice differentiable. Suppose that the line segment joining the points (0,f(0)) and (1,f(1)) intersects the graph of f at a point (a,f(a)), where 0< a < Then

A. there existsz∈[0,1] such thatf′(z) = 0
B. there existsz∈[0,1] such thatf′′(z) =|f(1)−f(0)|
C. there existsz∈[0,1] such thatf′′(z) =f(1)−f(0)
D. there existsz∈[0,1] such thatf′′(z) = 0

7 The set [0,1]

A. cannot be the intersection of a countable collection of sets of the form (a,b).
B. is the intersection of a countable collection of sets of the form (a,b).
C. is the union of a countable collection of sets of the form (a,b).
D. is the union of a countable collection of sets of the form $[a,a]$

8. A sequence of real numbers (xn) converges tox. Consider the following claims: (I) The sequence $(xnx+1n )$ converges to 1 (II) The sequencexn+xn+1converges to 2x.

A. Only statement II is correct.
B. Ouly Statement I is correct.
C. None of the statements is correct.
D. Both the statements are correct.

Persons 1, 2 and 3 have to divide 12 indivisible chocolates among themselves. Each person’s preference is strictly increasing in chocolates. The procedure for dividing the chocolates is as follows: Person 1 proposes a division. Each person votes either Y (Yes) or N (No). If at least two persons vote Y, then the proposal is implemented. If not, then Person 1 is eliminated from the voting and Person 2 makes a proposal. Now, only persons 2 and 3 can vote Y or N. If at least one of them votes Y, then Person 2’s proposal is implemented, Otherwise, Person 3 makes a proposal, which will be implemented.


9. What division of chocolates will occur from a subgame perfect.equilibrium of this game? (Assume that a person votes N if voting Y and N are expected to result in the same number of chocolates for that person.)

A. 1 gets 11, 2 gets 1. 3 gets 0

B. l gets 11, 2 gets 0, 3 gets 1

C. 1 gets 12, 2 gets 0, 3 gets 0

D. 1 gets 4, 2 gets 4, 3 gets 4


10. Suppose the above procedure for dividing the chocolates is changed as follows: if Person 1’s proposal is rejected and Person 2 makes a proposal, if both the remaining voters, 2 and 3, vote Y, then Person 2’s proposal is implemented. Otherwise, Person 3 makes a proposal, which will be implemented. What division of chocolates will occur from a subgame perfect equilibrium of this game? (Assume that a person votes N if voting Y and N are expected to result in the same number of chocolates for that person.)

A. 1 gets 11, 2 gets 1. 3 gets 0

B. l gets 11, 2 gets 0, 3 gets 1

C. 1 gets 12, 2 gets 0, 3 gets 0

D. 1 gets 4, 2 gets 4, 3 gets 4

11. The set {$f_1 ,f_2 ,...,f_n$ } where each $f_k$  is a real-valued function defined on R, is said to be linearly independent if $c_1 ,c_2 ,...,c_n \in R$ and $\sum c_k f_k (x) = 0$  for every $x\in R$ implies $c_1 =c_2 =···=c_n= 0$  Suppose $f_k(x) =x^k$ for all x\in R$ and $k= 1,...,n$ . Then,

A. the set {$f_1 ,...,f_n$ } is linearly independent.
B. each pair of these functions is linearly independent, but larger n-tuples are not.
C. only the subset of odd-numbered functions and the subset of even-numbered
functions are linearly independent.
D. every “proper subset of this set of functions is linearly independent, but the whole set is not.

12. Letf : $[0,1]→R$ be differentiable and suppose that $|f′(x)| <1$  for every $x\in[0,1]$ .Then, there
A. is at least one $c \in 0,1]$  such that $f(c) =c$.
B. are two numbersc 1 andc 2 such that $f(c_i) =c_i$ for $i= 1,2$ .
C. is exactly one $c\in [0,1]$  such that $f(c) =c$ .
D. is at most one $c\in[0,1]$  such that $f(c) =c$ .

13. Consider a closed macroeconomy whose demand side is represented by $Y =C_0 +c(Y−\tau Y)−\alpha r+G_0 M_0 =KPY−\beta r$ where $C_0 ,G_0 ,M_0 ,K,c,\tau,\alpha,\beta$ are all positive constants and $c,\tau \in (0,1)$. The AD curve for this economy is given by

A.  $Y =\frac{c_0+\frac{\alpha}{\beta} M_o +G_0}{1-c(1-\tau) }$
B.  $Y=\frac{C_0+M_0+G_0}{1-c(1-\tau) +\frac{\alpha}{\beta} KP}$
C.  $Y=\frac{C_0+M_0+G_0}{1-c(1-\tau) +KP}$
D.  $Y=\frac{C_0+M_0+G_0}{1-c(1-\tau) +\frac{KP}{\beta}}$


14. Consider a closed macroeconomy whose demand side is represented by $Y =C_0 +c(Y−\tau Y)−\alpha r+G_0 M_0 =KPY−\beta r$ where $C_0 ,G_0 ,M_0 ,K,c,\tau,\alpha,\beta$ are all positive constants and $c,\tau \in (0,1)$. . Now suppose the government, instead of following a given money supphy rule, follows an interest rate targeting policy such that the quantity ofmoney demanded is always supplied so as to keep the interest rate fixed at given level $r_0$. The AD curve for this economy is

A.  $Y =\frac{c_0+ ar_o +G_0}{1-c(1-\tau) }$

B.  $Y=\frac{C_0+M_0+G_0}{1-c(1-\tau) +KP}$

C.  $Y=\frac{C_0+M_0+G_0}{1-c(1-\tau) +\frac{KP}{\beta}}$

D.  $Y=\frac{C_0+M_0+G_0}{1-c(1-\tau) +\frac{\alpha}{\beta}KP}$



15. Consider a closed macroeconomy whose demand side is represented by $Y =C_0 +c(Y−\tau Y)−\alpha r+G_0 M_0 =KPY−\beta r$ where $C_0 ,G_0 ,M_0 ,K,c,\tau,\alpha,\beta$ are all positive constants and $c,\tau \in (0,1)$.  Suppose there an increase in the interest sensitivity of the IS curve (parameterα), which is accompanied by an increase in the (interest sensitivity of the LM curve (parameterβ) by exactly the same proportion. As a result,

A. the AD curve will be steeper but there will be no shift of the entire curve

B. the entire AD curve will shift to the right and it will also be steeper

C. the entire AD curve will shift to the right with no change in its slope

D. there will be no change in the AD curve (neither any change in its slope, nor  a shift)

16. In a multiple regression model involving three right-hand-side variables with 105 observations estimated using OLS, the researcher needs to decide whether to include a fourth right-had-side variable or not. The residual sum of squares is 250 when four variables are included and is 300 when three variables are included. Some critical values of the F-table  (with $\alpha= 0.05$) are: $F(1,100) = 3. 89 ,F(2,100) = 3. 09 ,F(3,100) = 2. 70 ,F(4,100) =2 .46$  andF(5,100) = 2.31. This means when the fourth variable is included, the fit of the regression

A. there is insufficient information to make a determination about fit

B. worsens significantly

C. has no significant change

D. improves significantly


17. For a variable x the standard error of the sample mean is calculated as 20 when samples of size 25 are taken and as 10 when samples of size 100 are taken. A quadrupling of sample size has only halved the error. What must be the value of the standard error of x?

A.  1000

B.   900

C.  100

D.   377.5


18. Suppose a consumer lives for two periods and chooses consumptions $C_1$ and $C_2$ to maximise utility $U(C_T) = \frac{\sigma}{\sigma-1}(C_t^{(\frac{\sigma -1}{\sigma} -1)})$ Future consumption is discounted by $\sigma$ . The intertemporal elasticity of substitution in consumption between the two periods is

A.   $\sigma$

B.   $1$

C.   $\frac{\sigma -1}{\sigma}$

D.   $\frac{\sigma}{\sigma-1}$


19. Consider the game where the row player’s payoff is given first, followed by the column player’s payoff. Which of the following statements is false?

$$
\left(\begin{array}{cc} 
2,0 & 3,3 & 0,0 \\
-1,1 & 0,0 & 1,0 \\
4,-4 & 2,2 & 1,1
\end{array}\right)
$$ 

A. There is a Nash equilibrium of this game in which the column player plays a strictly dominated strategy.
 
B. Column player has a strictly dominated strategy.

C. Row player has a weakly dominated strategy.

D. There is a Nash equilibrium of this game in which both players play weakly dominated strategies.


20. In a multiple regression model, the Durbir Watson test statistic is 1.3, while the critical lower and upper values are 1.5 and 1.7 respectively. This implies that

A. There is positive autocorrelation,

B. There is no positive autocorrelation:

C. The test is inconclusive about autocorrelation.

D. There is heteroscedasticity but no autocorrelation.


21. Consider the modely = $\beta_0 +\beta_1 X_1 +\beta_2 X_2$ estimated using OLS. Which of the following will lead to a higher $Var(\hat \beta_2 )$?
       - Smaller sample size
       - Less variation in $X_2$
       - More variation in
       - High correlation between $X_1$ and $X_2$

The correct answer is:

A. (i), (ii), (iii) and (iv)

B. (ii), (iii) and (iv)

C. (ii) and (iii)

D. (iii) and (iv)

22. Consider an exchange economy with two agents, 1 and 2, and two goods, X and Y. Each agent’s consumption set is $R^2$  The endowments of agents 1 and 2 are (10,1) and (0,9) respectively. (In any commodity bundle, the first entry is a quantity of X and the second one is a quantity of Y.) Ifa > c, ora=candb > d, then Agent 1 strictly prefers bundle (a,b) to (b,d). Ifb > d, orb=danda > c, then Agent 1 strictly prefers bundle (a,b) to (b,d). Which of the following allocations is an efficient allocation?

A. 1 gets (5,5) and 2 gets (5,5)

B. 1 gets (10,1) and 2 gets (0,9)

C. 1 gets (10,10) and 2 gets (0.0)

D. All of the above

E. Incorrect options provided for this question.

23. Consider a country with two citizens, 1 and 2. The government is considering a scheme  that will cost 100. The government does not know the true benefits of the scheme to the  citizens, sayB 1 , andB 2 , and must decide whether to implement the scheme on the basis  of their reported benefits. sayR 1 andR 2. It will implement the scheme if and only ifR 1 +R 2 ≥100. If it is implemented, the government will impose tax 100−R 2 on person 1 and tax 100−R 1 , on person 2. Each citizen’s reported benefit seeks to maximize the difference between her true benefit (known only to her) and the tax that must be paid if  and only if the scheme is implemented. The optimal choices ofR 1 andR 2 must be such that

A. $R_1 < B_1$ and $R_2 < B_2$

B. Nothing systematic can be said about  $R_1$ and $R_2$

C. $R_1 =B_1$ and $R_2 =B_2$

D. $R_1 > B_1$ and $R_2 > B_2$


Consider a Solovian economy with the aggregate production function $Y_t = K$ .  Initial size of the population is 100 and the initial capital stock is given by 9 units. The entire output produced in each period is distributed to the households as factor incomes(since households are the owners of the capital stock and Jabour at any time t), who consume half of their income and save the rest. All savings are automatically invested which augment the capital stock available for production over time. Population does not grow and there is 100% depreciation of capital stock within one period.

24. The corresponding steady state value of aggregate output is

A.  30

B.  50

C.  5

D.  10

25. The corresponding steady state value of aggregate consumption is

A.  50

B.  10

C.  30

D.  25

26. The steady state value of aggregate capital stock is

A.  9

B.  25

C.  2.5

D.  10

27. Suppose households were free to choose their savings rate. If they wanted to maximize the steady state level of consumption, the savings rate would be

A.  $\frac{1}{2}$

B.  $\frac{1}{4}$

C.  $\frac{1}{5}$

D.  $\frac{1}{10}$

28. In the previous problem, where households choose their savings rate, at that savings rate, the steady state value of the aggregate capital stock is

A.  25

B.  2.5

C.  10

D.   9

E.   Incorrect options provided for this question.


29. Suppose $X_1 ,...,X_n$ are observed completion times of an experiment with values in $[0,1]$ . Each of these random variables is uniformly distributed on (0,1). If Y is the maximum observed completion time, then the mean of Y is

A.   $\frac{n}{2(n+1)}$

B.   $\frac{2n}{n+1}$

C.   $(\frac{n}{(n+1)})^2$

D.   $\frac{n}{n+1}$

30. If $f:R^2 →R$ is given by then

A. f is differentiable at (0,0) and both partial derivatives at (0,0) are 0

B. f is non-differentiable at (0,0) and both partial derivatives at (0,0) are 0

C. f is differentiable at (0,0) and neither partial derivatives at (0,0) is 0

D. f is non-differentiable at (0,0) and neither partial derivatives at (0,0) exist

31. Suppose we have estimated $y= 10 + 1. 5 x+ 4D$ , where y is earnings, << is experience and D is 0 for females and 1 for males. If we had coded the dummy as −1  for females and 1 for males, the new estimated coefficients (in the same order) would have been:

A.  12, 1. 5 ,− 2

B.  12, 4. 5 , 2

C.  14, 1. 5 ,− 4

D.  10, 1. 5. 4

32. Which of the following is/are the consequence(s) of including an irrelevant variable in a multiple linear regression model? (i) The variances of the OLS coefficients may be larger (ii) The OLS coefficients will be biased unless the irrelevant variable is orthogonal to the other included variables (iii) The variances of the OLS coefficients will be unaffected. The correct answer is:

A. (i) only

B. (ii) and (iii) only

C. (iii) only

D.  (i) and (ii)

33. Suppose Y is a random variable with uniform distribution of the interval $[−\frac{\pi}{2}  ,\frac{\pi}{2}]$. The value of the (cumulative) distribution function of th ́e random variable $X=\sin Y$ at $x\in [−  1 ,1]$ is

---
DRAFT
---

34. A student is answering a multiple-choice examination. Suppose a question hasmpossible answers. The student knows the correct answer with probabilityp. If the student knows the correct answer, then she picks that answer; otherwise, she picks randomly from the choices with probability $1\frac{1}{m}$ each. Given that the student picked the correct answer, the probability that she knew the correct answer is

A.  $\frac{p}{1+(1-p)m}$

B.  $\frac{p}{1+(m-1)p}$

C.  $\frac{mp}{1+(1-p)m}$

D.  $\frac{mp}{1+(m-1)p}$

35. Consider the game where the row player’s payoff is given first, followed by the column player’s payoff. This game has only one Nash equilibrium when

A.  $x > y > z$

B.  $x < y < z$

C.  $x=y=z$

D.  $y > z > x$


36. Consider an economy where there is no capital. Production of the final good is carried out in each period using a linear production function that uses only labour. The production  technology is specified as follows: $Y_t=A_t(1−\lambda _t)L_0$  where $L_0$  is the constant labour force in the economy, $1−\lambda _t$ , is the proportion of labour force engaged in final goods production andAtis the state of technology in period t. The index of technology At changes over time depending on the proportion of the labour force engaged in R&D, which is $\lambda_t$. The evolution of technology in the R&D sector is determined by the equation $\frac{dA}{dt} =\lambda _t L_0A_t$  where the initial $A_0$  is a positive constant. Now suppose that the relative price of the new technologies generated in the R&D sector in terms of the final commodity is unity. Also suppose the labour across two sectors are employed in such a way that the value of marginal product of labour across the two sectors are identical. In this case, the equilibrium value of $\lambda _t$ will be

A.  $\lambda _0$

B.  $\frac{1}{2}$

C.  $1$

D.  $1-\lambda _0$


37. Consider an economy where there is no capital. Production of the final good is carried out in each period using a linear production function that uses only labour. The production  technology is specified as follows: $Y_t=A_t(1−\lambda _t)L_0$  where $L_0$  is the constant labour force in the economy, $1−\lambda _t$ , is the proportion of labour force engaged in final goods production andAtis the state of technology in period t. The index of technology At changes over time depending on the proportion of the labour force engaged in R&D, which is $\lambda_t$. The evolution of technology in the R&D sector is determined by the equation $\frac{dA}{dt} =\lambda _t L_0A_t$  where the initial $A_0$  is a positive constant.  For any exogenously given value of $\lambda_t=\lambda_0$  , the long run balanced growth rate in this economy is

A.  $(1-\lambda _0)L_0$

B.  $(1-\lambda _0)$

C.  $\lambda _0$

D.  $\lambda _0 L_0$


38. Duopolist firms 1 and 2 sell a homogeneous good in a market with demand function Q = 100− 2 P, whereQis the quantity demanded at priceP. Firms 1 and 2 have constant marginal costs of 0 and 30 respectively. The firms simultaneously announce prices and consumers buy from the firm whose price is lower. If the firms choose the same price, all the consumers buy from firm 1. Firm 1’s equilibrium price is

A. 30

B. 0

C. 25

D. 20

39. Voters arrive at a social ranking of alternatives by consulting a “holy book”: the social ranking is the ranking found in this book. Which of Arrow’s axioms defining an attractive preference aggregation method is violated by this method?

A. Independence of irrelevant alternatives

B. Non-dictatorship

C. Unrestricted domain

D. The Pareto principle

40. A consumer weakly prefers a basket $(a_1 ,a_2 ,a_3 )$ to a basket  $(b_1 ,b_2 ,b_3 )$ if $a_1 \geq b_1 ,a_1 +a_2 \geq  b_1 +b_2 ,a_1 +a_2 +a_3 \geq b_1 +b_2 +b_3$ Which of the following statements about this preference is false?

A. It is transitive.

B. It is monotonic.

C. It is continuous.

D. It is complete,

41. Suppose the economy-wide union sets wage for employed workers by $W=P^e(Z−\alpha u)$ with unemployment rate u and labour force of the economy L. The producer levies price over wage W with mark-up m as $P= (1 +m)W$ . If each employed worker produces one unit of output Y, then the aggregate supply function is

A.  $P=−P^e(1 +m)(Z−1 +\frac{\alpha Y}{L})$

B.  $P=  P^e(1 +m)(Z−1 +\frac{\alpha Y}{L})$

C.  $P=−P^e(1 +m)(Z−\alpha +\frac{\alpha Y}{L})$

D.  $P=P^e(1 +m)(Z−\alpha +\frac{\alpha Y}{L})$

42. Consider the following regression modelyi=α 0 +α 1 x 1 i+α 2 x 2 i+uiSuppose a researcher is interested in conducting White’s heteroscedasticity test using the residuals from an estimation of the above equation. What would be the most appropriate form for the auxiliary regression?

A.   $u_i^2=\gamma_0 +\gamma_1 x_{1i}+\gamma_2 x_{2i}+\gamma_3 x_{1i}^2+\gamma_4 x_{2i}^2+\gamma_5 x_{1i} x_{2i}+ v_i$

B.   $u_i^2=\gamma_0 +\gamma_1 u_i− 1 +v_i$

C.   $u_i^2=\gamma_0 +\gamma_1 x_{1i}+\gamma_2 x_{2i} +\gamma_3 x{1i}^2+\gamma_4 x_{2i}^2+v_i$

D.   $u_i=\gamma_0 +\gamma_1 u_i− 1 +v_i$

43. Suppose you have run the following regression: $y=\alpha+\beta x+ \gamma Urban +\theta Immigration + \sigma UrbanImmigration$  where Urban is a dummy indicating that the person lives in a city rather than a rural area, Immigrant is a dummy indicating that the person is an immigrant rather than a native. The coefficientθis interpreted as the ceteris paribus difference in y between

A.  A rural immigrant and a rural native

B.  An immigrant and a native

C.  An urban immigrant and an urban native

D.  None of the above

44. Consider an exchange economy with two agents, 1 and 2, and two goods, X and Y. Each agent’s consumption set is $R_+^2$ . Given bundles $(a,b),(c,d)\in R^2$ such that $(a,b)≥(c,d)$  and $(a,b) \neq = (c,d)$ , agent 1 strictly prefers (a,b). (In any commodity bundle, the first entry is a quantity of X and the second one is a quantity of Y.) Consider the following claims: In a competitive equilibrium for this economy, (I) both prices must be positive, and (II) the sum of the allocations to 1 and 2 must equal the sum of their endowments. Which of the following statements is correct?

A. i and ii are true

B. i and ii are false

C. i is true and ii is false

D. i is false and ii is true

45. A monopolist faces a demand function $D(p) =\alpha−p$ and cost function $C(q) =cq$. She can advertise her product to increase demand. Advertisement level $\theta$ costs $\frac{\theta ^2 }{2}$ and it shifts the demand function by $\theta$  i.e., the new demand function is $D(p) =\alpha +\theta −p$ .The monopolist’s profit is

A.   $\frac{(\alpha−  c)^2}{4}$

B.   $\frac{(\alpha−  c)^2}{2}$

C.   $\frac{(\alpha−  c-\theta)^2}{2}$

D.   $(\alpha−  \theta)^2$

46. Consider the following game. Player 1 moves first and chooses L or R. If she plays R, the game ends and the payoffs are (10,0). If she plays L, then player 2 moves and chooses cither L or R. If he plays R, the game ends and the payoffs are (0,20). If he plays L, then player 1 moves and chooses either L or R. The game ends in both cases. If player  chooses L, then the payoffs are (30.30). If she chooses L, then the payoffs are (40,0). This game

A. bas three subgame perfect equilibria

B. has a unique Nash equilibrium

C. has a subgame perfect equilibrium in which 2 plays L

D. has a unique Nash equilibrium outcome

47. If the function $f:R^2 →R$ is concave, then

A. {$(x,r)∈R^2 ×R|f(x)< r$ } is convex

B. {$(x,r)∈R^2 ×R|f(x) =r$}  is convex

C. {$(x,r)∈R^2 ×R|f(x)≥r$}  is convex

D. {$(x,r)∈R^2 ×R|f(x)≤r$}  is convex

48. Let R be the set of real numbers. A subset of R, say E, is said to be open-if for every  $x\in E$ , there exists $r >0$ ,  such that $(x−r,x+r)$  is a subset of E. Then, 

A. $E_1 ∩···∩ E_n$  is open, for every collection of open sets {$E_1 ,...,E_n$} 

B. $E_1 ∪···∪ E_n$ is open, for every collection of open sets {$E_1 ,...,E_n$}

C. φ is open

D. all of the above are true

49. You have 100 observations on y with average value 15, and on x, with average value 8. From an OLS regression, you have estimated the slope on x to be 2. Your estimate of the mean of y conditioned on x is

A. 15

B. 16

C. 17

D. None of the above

50. Suppose your data produces the regression result $y= 10 + 3x$. Scale $y$ by multiplying observations by $0.9$  and do not scale $x$. The new intercept and slope estimates will be

A.  10 and 3

B.   9 and 3

C.   9 and 2.7

D.  10 and 2.7
