---
title: "Untitled"
author: "dhananjaya"
date: "02/09/2022"
fontsize: "24pt"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: zenburn
    fig_width: 7
    fig_height: 6
    fig_caption: true
    df_print: paged
    toc_depth: 4
---


# Historical Background

The British came to India in 1600 as traders, in the form of East India Company, which had the exclusive right of
trading in India under a charter granted by Queen Elizabeth I. In 1765, the Company, which till now had purely trading functions obtained the ‘diwani’ (i.e., rights over revenue and civil justice) of Bengal, Bihar and Orissa. This started its career as a territorial power. In 1858, in the wake of the ‘sepoy mutiny’, the British Crown assumed direct responsibility for the governance of India. This rule continued until India was granted independence.on August 15, 1947.With Independence came the need for a Constitution. Hence, a Constituent Assembly was formed for this purpose in 1946 and on January 26, 1950, the Constitution came into being. However various features of the Indian Constitution and polity have their
roots in the British rule. There were certain events in the British
rule that laid down the legal framework for the organisation and
functioning of government and administration in British India.
These events have greatly influenced our constitution and polity.
They are explained here in a chronological order under two major
headings :

1. The Company Rule (1773 – 1858)
2. The Crown Rule (1858 – 1947)


## THE COMPANY RULE (1773–1858) 

### Regulating Act of 1773

This act was of great constitutional importance as (a) it was the
first step taken by the British Government to control and regulate
the affairs of the East India Company in India; (b) it recognised,
for the first time, the political and administrative functions of the
Company; and (c) it laid the foundations of central administration
in India.

_The features of this Act were as follows:_

1. It designated the Governor of Bengal as the ‘Governor-
    General of Bengal’ and created an Executive Council of four
    members to assist him. The first such GovernorGeneral was
    Lord Warren Hastings.
2. It made the governors of Bombay and Madras presidencies
    subordinate to the governor-general of Bengal, unlike earlier,
    when the three presidencies were independent of one
    another.
3. It provided for the establishment of a Supreme Court at
    Calcutta (1774) comprising one chief justice and three other
    judges.
4. It prohibited the servants of the Company from engaging in
    any private trade or accepting presents or bribes from the
    ‘natives’.
5. It strengthened the control of the British Government over
    the Company by requiring the Court of Directors (governing
    body of the Company) to report on its revenue, civil, and
    military affairs in India.

### Amending Act of 1781

In a bid to rectify the defects of the Regulating Act of 1773, the
British Parliament passed the Amending Act of 1781, also known
as the Act of Settlement.

_The features of this Act were as follows:_


1. It exempted the Governor-General and the Council from the  jurisdiction of the SupremCourt for the acts done by them
    in their official capacity. Similarly, it also exempted the
    servants of the company from the jurisdiction of the
    Supreme Court for their official actions.
2. It excluded the revenue matters and the matters arising in
    the collection of revenue from the jurisdiction of the Supreme
    Court.
3. It provided that the Supreme Court was to have jurisdiction
    over all the inhabitants of Culcutta. It also required the court
    to administer the personal law of the defendants i.e., Hindus
    were to be tried according to the Hindu law and Muslims
    were to be tried according to the Mohammedan law.
4. It laid down that the appeals from the Provincial Courts
    could be taken to the Governor-General-in-Council and not
    to the Supreme Court.
5. It empowered the Governor-General-inCouncil to frame
    regulations for the Provincial Courts and Councils.

### Pitt’s India Act of 1784

The next important act was the Pitt’s India Act^2 of 1784.

_The features of this Act were as follows:_

1. It distinguished between the commercial and political
    functions of the Company.
2. It allowed the Court of Directors to manage the commercial
    affairs, but created a new body called Board of Control to
    manage the political affairs. Thus, it established a system of
    double government.
3. It empowered the Board of Control to supervise and direct
    all operations of the civil and military government or
    revenues of the British possessions in India.
Thus, the act was significant for two reasons: first, the
Company’s territories in India were for the first time called the
‘British possessions in India’; and second, the British Government
was given the supreme control over Company’s affairs and its
administration in India.


### Act of 1786

In 1786, Lord Cornwallis was appointed as the Governor-General
of Bengal. He placed two demands to accept that post, viz.,

1. He should be given power to override the decision of his
    council in special cases.
2. He would also be the Commander-in-Chief.
Accordingly, the Act of 1786 was enacted to make both the
provisions.

### Charter Act of 1793

_The features of this Act were as follows:_

1. It extended the overriding power given to Lord Cornwallis
    over his council, to all future Governor-Generals and
    Governors of Presidencies.
2. It gave the Governor-General more powers and control over
    the governments of the subordinate Presidencies of Bombay
    and Madras.
3. It extended the trade monopoly of the Company in India for
    another period of twenty years.
4. It provided that the Commander-in-Chief was not to be a
    member of the Governor-General’s council, unless he was
    so appointed.
5. It laid down that the members of the Board of Control and
    their staff were, henceforth, to be paid out of the Indian
    revenues.

### Charter Act of 1813

_The features of this Act were as follows:_

1. It abolished the trade monopoly of the company in India i.e.,
    the Indian trade was thrown open to all British merchants.
    However, it continued the monopoly of the company over
    trade in tea and trade with China.
2. It asserted the sovereignty of the British Crown over the
    Company’s territories in India.
3. It allowed the Christian missionaries to come to India for the
    purpose of enlightening the people.


4. It provided for the spread of western education among the
    inhabitants of the British territories in India.
5. It authorised the Local Governments in India to impose
    taxes on persons. They could also punish the persons for
    not paying taxes.

### Charter Act of 1833

This Act was the final step towards centralisation in British India.

_The features of this Act were as follows:_

1. It made the Governor-General of Bengal as the Governor-
    General of India and vested in him all civil and military
    powers. Thus, the act created, for the first time, Government
    of India having authority over the entire territorial area
    possessed by the British in India. Lord William Bentick was
    the first Governor-General of India.
2. It deprived the Governor of Bombay and Madras of their
    legislative powers. The Governor-General of India was given
    exclusive legislative powers for the entire British India. The
    laws made under the previous acts were called as
    Regulations, while laws made under this act were called as
    Acts.
3. It ended the activities of the East India Company as a
    commercial body, which became a purely administrative
    body. It provided that the Company’s territories in India were
    held by it ‘in trust for His Majesty, His heirs and successors’.
4. The Charter Act of 1833 attempted to introduce a system of
    open competition for selection of civil servants and stated
    that the Indians should not be debarred from holding any
    place, office and employment under the Company. However,
    this provision was negated after opposition from the Court of
    Directors.

Charter Act of 1853

This was the last of the series of Charter Acts passed by the
British Parliament between 1793 and 1853. It was a significant
constitutional landmark.


_The features of this Act were as follows:_

1. It separated, for the first time, the legislative and executive
    functions of the Governor-General’s council. It provided for
    addition of six new members called legislative councillors to
    the council. In other words, it established a separate
    Governor-General’s legislative council which came to be
    known as the Indian (Central) Legislative Council. This
    legislative wing of the council functioned as a mini-
    Parliament, adopting the same procedures as the British
    Parliament. Thus, legislation, for the first time, was treated
    as a special function of the government, requiring special
    machinery and special process.
2. It introduced an open competition system of selection and
    recruitment of civil servants. The covenanted civil service^3
    was, thus, thrown open to the Indians also. Accordingly, the
    Macaulay Committee (the Committee on the Indian Civil
    Service) was appointed in 1854.
3. It extended the Company’s rule and allowed it to retain the
    possession of Indian territories on trust for the British Crown.
    But, it did not specify any particular period, unlike the
    previous Charters. This was a clear indication that the
    Company’s rule could be terminated at any time the
    Parliament liked.
4. It introduced, for the first time, local representation in the
    Indian (Central) Legislative Council. Of the six new
    legislative members of the GovernorGeneral’s council, four
    members were appointed by the local (provincial)
    governments of Madras, Bombay, Bengal and Agra.


## THE CROWN RULE (1858–1947)

### Government of India Act of 1858

This significant Act was enacted in the wake of the Revolt of
1857–also known as the First War of Independence or the ‘sepoy
mutiny’. The act known as the Act for the Good Government of
India, abolished the East India Company, and transferred the
powers of Government, territories and revenues to the British
Crown.

_The features of this Act were as follows:_

1. It provided that India, henceforth, was to be governed by,
    and in the name of, Her Majesty. It changed the designation
    of the Governor-General of India to that of Viceroy of India.
    He (Viceroy) was the direct representative of the British
    Crown in India. Lord Canning, thus, became the first Viceroy
    of India.
2. It ended the system of double Government by abolishing the
    Board of Control and Court of Directors.
3. It created a new office, Secretary of State for India, vested
    with complete authority and control over Indian
    administration. The secretary of state was a member of the
    British Cabinet and was responsible ultimately to the British
    Parliament.
4. It established a 15-member council of India to assist the
    Secretary of State for India. The council was an advisory
    body. The secretary of state was made the Chairman of the
    council.
5. It constituted the Secretary of State-inCouncil as a body
    corporate, capable of suing and being sued in India and in
    England.
‘The Act of 1858 was, however, largely confined to the
improvement of the administrative machinery by which the Indian
Government was to be supervised and controlled in England. It
did not alter in any substantial way the system of Government that

prevailed in India^4 .’


### Indian Councils Act of 1861

After the great revolt of 1857, the British Government felt the
necessity of seeking the cooperation of the Indians in the
administration of their country. In pursuance of this policy of
association, three acts were enacted by the British Parliament in
1861, 1892 and 1909. The Indian Councils Act of 1861 is an
important landmark in the constitutional and political history of
India.

_The features of this Act were as follows:_

1. It made a beginning of the representative institutions by
    associating Indians with the law-making process. It, thus,
    provided that the Viceroy should nominate some Indians as
    non-official members of his expanded council. In 1862, Lord
    Canning, the then Viceroy, nominated three Indians to his
    legislative council–the Raja of Benaras, the Maharaja of
    Patiala and Sir Dinkar Rao.
2. It initiated the process of decentralisation by restoring the
    legislative powers to the Bombay and Madras Presidencies.
    It, thus, reversed the centralising tendency that started from
    the Regulating Act of 1773 and reached its climax under the
    Charter Act of 1833. This policy of legislative devolution
    resulted in the grant of almost complete internal autonomy to
    the provinces in 1937.
3. It also provided for the establishment of new legislative
    councils for Bengal, North-Western Provinces and Punjab,
    which were established in 1862, 1886 and 1897,
    respectively.
4. It empowered the Viceroy to make rules and orders for the
    more convenient transaction of business in the council. It
    also gave a recognition to the ‘portfolio’ system, introduced
    by Lord Canning in 1859. Under this, a member of the
    Viceroy’s council was made in-charge of one or more
    departments of the Government and was authorised to issue
    final orders on behalf of the council on matters of his
    department(s).
5. It empowered the Viceroy to issue ordinances, without the
    concurrence of the legislative council, during an emergency.



The life of such an ordinance was six months.

### Indian Councils Act of 1892

_The features of this Act were as follows:_

1. It increased the number of additional (non-official) members
    in the Central and provincial legislative councils, but
    maintained the official majority in them.
2. It increased the functions of legislative councils and gave
    them the power of discussing the budget^5 and addressing
    questions to the executive.
3. It provided for the nomination of some non-official members
    of the (a) Central Legislative Council by the viceroy on the
    recommendation of the provincial legislative councils and the
    Bengal Chamber of Commerce, and (b) that of the provincial
    legislative councils by the Governors on the
    recommendation of the district boards, municipalities,
    universities, trade associations, zamin-dars and chambers.
‘The act made a limited and indirect provision for the use of
election in filling up some of the non-official seats both in the
Central and provincial legislative councils. The word “election”
was, however, not used in the Act. The process was described as

nomination made on the recommendation of certain bodies^6 .’

### Indian Councils Act of 1909

This Act is also known as Morley-Minto Reforms (Lord Morley was
the then Secretary of State for India and Lord Minto was the then
Viceroy of India).

_The features of this Act were as follows:_

1. It considerably increased the size of the legislative councils,
    both Central and provincial. The number of members in the
    Central legislative council was raised from 16 to 60. The
    number of members in the provincial legislative councils was
    not uniform.
2. It retained official majority in the Central legislative council,
    but allowed the provincial legislative councils to have non-
    official majority.


3. It enlarged the deliberative functions of the legislative
    councils at both the levels. For example, members were
    allowed to ask supplementary questions, move resolutions
    on the budget and so on.
4. It provided (for the first time) for the association of Indians
    with the executive councils of the Viceroy and Governors.
    Satyendra Prasad Sinha became the first Indian to join the
    Viceroy’s executive council. He was appointed as the Law
    Member.
5. It introduced a system of communal representation for
    Muslims by accepting the concept of ‘separate electorate’.
    Under this, the Muslim members were to be elected only by
    Muslim voters. Thus, the Act ‘legalised communalism’ and
    Lord Minto came to be known as the Father of Communal
    Electorate.
6. It also provided for the separate representation of
    presidency corporations, chambers of commerce,
    universities and zamindars.

### Government of India Act of 1919

On August 20, 1917, the British Government declared, for the first
time, that its objective was the gradual introduction of responsible
Government in India^7.
The Government of India Act of 1919 was thus enacted, which
came into force in 1921. This Act is also known as Montagu-
Chelmsford Reforms (Montagu was the Secretary of State for
India and Lord Chelmsford was the Viceroy of India).

_The features of this Act were as follows:_

1. It relaxed the central control over the provinces by
    demarcating and separating the central and provincial
    subjects. The central and provincial legislatures were
    authorised to make laws on their respective list of subjects.
    However, the structure of government continued to be
    centralised and unitary.
2. It further divided the provincial subjects into two parts–
    transferred and reserved. The transferred subjects were to
    be administered by the Governor with the aid of Ministers



responsible to the legislative council. The reserved subjects,
on the other hand, were to be administered by the Governor
and his executive council without being responsible to the
legislative council. This dual scheme of governance was
known as ‘dyarchy’–a term derived from the Greek word di-
arche which means double rule. However, this experiment
was largely unsuccessful.

3. It introduced, for the first time, bicameralism and direct
    elections in the country. Thus, the Indian legislative council
    was replaced by a bicameral legislature consisting of an
    Upper House (Council of State) and a Lower House
    (Legislative Assembly). The majority of members of both the
    Houses were chosen by direct election.
4. It required that the three of the six members of the Viceroy’s
    executive Council (other than the Commander-in-Chief)
    were to be Indian.
5. It extended the principle of communal representation by
    providing separate electorates for Sikhs, Indian Christians,
    Anglo-Indians and Europeans.
6. It granted franchise to a limited number of people on the
    basis of property, tax or education.
7. It created a new office of the High Commissioner for India in
    London and transferred to him some of the functions hitherto
    performed by the Secretary of State for India.
8. It provided for the establishment of a public service
    commission. Hence, a Central Public Service Commission
    was set up in 1926 for recruiting civil servants^8.
9. It separated, for the first time, provincial budgets from the
    Central budget and authorised the provincial legislatures to
    enact their budgets.
10. It provided for the appointment of a statutory commission to
inquire into and report on its working after ten years of its
coming into force.

### Simon Commission
In November 1927 itself (i.e., 2 years before the schedule), the
British Government announced the appointment a seven-member
statutory commission under the chairmanship of Sir John Simon


to report on the condition of India under its new Constitution. All
the members of the commission were British and hence, all the
parties boycotted the commission. The commission submitted its
report in 1930 and recommended the abolition of dyarchy,
extension of responsible Government in the provinces,
establishment of a federation of British India and princely states,
continuation of communal electorate and so on. To consider the
proposals of the commission, the British Government convened
three round table conferences of the representatives of the British
Government, British India and Indian princely states. On the basis
of these discussions, a ‘White Paper on Consitutional Reforms’
was prepared and submitted for the consideration of the Joint
Select Committee of the British Parliament. The recommendations
of this committee were incorporated (with certain changes) in the
next Government of India Act of 1935.

Communal Award
In August 1932, Ramsay MacDonald, the British Prime Minister,
announced a scheme of representation of the minorities, which
came to be known as the Communal Award. The award not only
continued separate electorates for the Muslims, Sikhs, Indian
Christians, Anglo-Indians and Europeans but also extended it to
the depressed classes (Scheduled Castes). Gandhiji was
distressed over this extension of the principle of communal
representation to the depressed classes and undertook fast unto
death in Yerawada Jail (Poona) to get the award modified. At last,
there was an agreement between the leaders of the Congress and
the depressed classes. The agreement, known as Poona Pact,
retained the Hindu joint electorate and gave reserved seats to the
depressed classes.

### Government of India Act of 1935

The Act marked a second milestone towards a completely
responsible government in India. It was a lengthy and detailed
document having 321 Sections and 10 Schedules.

_The features of this Act were as follows:_


1. It provided for the establishment of an All-India Federation
    consisting of provinces and princely states as units. The Act
    divided the powers between the Centre and units in terms of
    three lists–Federal List (for Centre, with 59 items), Provincial
    List (for provinces, with 54 items) and the Concurrent List
    (for both, with 36 items). Residuary powers were given to the
    Viceroy. However, the federation never came into being as
    the princely states did not join it.
2. It abolished dyarchy in the provinces and introduced
    ‘provincial autonomy’ in its place. The provinces were
    allowed to act as autonomous units of administration in their
    defined spheres. Moreover, the Act introduced responsible
    Governments in provinces, that is, the Governor was
    required to act with the advice of ministers responsible to the
    provincial legislature. This came into effect in 1937 and was
    discontinued in 1939.
3. It provided for the adoption of dyarchy at the Centre.
    Consequently, the federal subjects were divided into
    reserved subjects and transferred subjects. However, this
    provision of the Act did not come into operation at all.
4. It introduced bicameralism in six out of eleven provinces.
    Thus, the legislatures of Bengal, Bombay, Madras, Bihar,
    Assam and the United Provinces were made bicameral
    consisting of a legislative council (upper house) and a
    legislative assembly (lower house). However, many
    restrictions were placed on them.
5. It further extended the principle of communal representation
    by providing separate electorates for depressed classes
    (Scheduled Castes), women and labour (workers).
6. It abolished the Council of India, established by the
    Government of India Act of 1858. The secretary of state for
    India was provided with a team of advisors.
7. It extended franchise. About 10 per cent of the total
    population got the voting right.
8. It provided for the establishment of a Reserve Bank of India
    to control the currency and credit of the country.
9. It provided for the establishment of not only a Federal Public
    Service Commission, but also a Provincial Public Service



Commission and Joint Public Service Commission for two or
more provinces.

10. It provided for the establishment of a Federal Court, which
    was set up in 1937.

### Indian Independence Act of 1947

On February 20, 1947, the British Prime Minister Clement Atlee
declared that the British rule in India would end by June 30,1948;
after which the power would be transferred to responsible Indian
hands. This announcement was followed by the agitation by the
Muslim League demanding partition of the country. Again on June
3, 1947, the British Government made it clear that any
Constitution framed by the Constituent Assembly of India (formed
in 1946) cannot apply to those parts of the country which were
unwilling to accept it. On the same day (June 3, 1947), Lord
Mountbatten, the Viceroy of India, put forth the partition plan,
known as the Mountbatten Plan. The plan was accepted by the
Congress and the Muslim League. Immediate effect was given to
the plan by enacting the Indian Independence Act^9 (1947).

_The features of this Act were as follows:_

1. It ended the British rule in India and declared India as an
    independent and sovereign state from August 15, 1947.
2. It provided for the partition of India and creation of two
    independent dominions of India and Pakistan with the right
    to secede from the British Commonwealth.
3. It abolished the office of Viceroy and provided, for each
    dominion, a governorgeneral, who was to be appointed by
    the British King on the advice of the dominion cabinet. His
    Majesty’s Government in Britain was to have no
    responsibility with respect to the Government of India or
    Pakistan.
4. It empowered the Constituent Assemblies of the two
    dominions to frame and adopt any constitution for their
    respective nations and to repeal any act of the British
    Parliament, including the Independence act itself.
5. It empowered the Constituent Assemblies of both the
    dominions to legislate for their respective territories till the



new constitutions were drafted and enforced. No Act of the
British Parliament passed after August 15, 1947 was to
extend to either of the new dominions unless it was
extended thereto by a law of the legislature of the dominion.

6. It abolished the office of the Secretary of State for India and
    transferred his functions to the Secretary of State for
    Commonwealth Affairs.
7. It proclaimed the lapse of British paramountcy over the
    Indian princely states and treaty relations with tribal areas
    from August 15, 1947.
8. It granted freedom to the Indian princely states either to join
    the Dominion of India or Dominion of Pakistan or to remain
    independent.
9. It provided for the governance of each of the dominions and
    the provinces by the Government of India Act of 1935, till the
    new Constitutions were framed. The dominions were
    however authorised to make modifications in the Act.
10. It deprived the British Monarch of his right to veto bills or ask
for reservation of certain bills for his approval. But, this right
was reserved for the GovernorGeneral. The Governor-
General would have full power to assent to any bill in the
name of His Majesty.
11. It designated the Governor-General of India and the
provincial governors as constitutional (nominal) heads of the
states. They were made to act on the advice of the
respective council of ministers in all matters.
12. It dropped the title of Emperor of India from the royal titles of
the King of England.
13. It discontinued the appointment to civil services and
reservation of posts by the secretary of state for India. The
members of the civil services appointed before August 15,
1947 would continue to enjoy all benefits that they were
entitled to till that time.
At the stroke of midnight of 14-15 August, 1947, the British rule
came to an end and power was transferred to the two new
independent Dominions of India and Pakistan^10. Lord Mountbatten
became the first GovernorGeneral of the new Dominion of India.
He swore in Jawaharlal Nehru as the first Prime Minister of


independent India. The Constituent Assembly of India formed in
1946 became the Parliament of the Indian Dominion.